// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFP7vkmOdxLiekbs19Rm6Mz39sQUeLamk',
    appId: '1:529715404420:web:aa88b7bc2faacdbcf12cd1',
    messagingSenderId: '529715404420',
    projectId: 'movie-and-tv-series-app',
    authDomain: 'movie-and-tv-series-app.firebaseapp.com',
    storageBucket: 'movie-and-tv-series-app.appspot.com',
    measurementId: 'G-5BP45KFPDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2uV8kAp0QsA3Lt9PK63SqH2iMU9oPwUM',
    appId: '1:529715404420:android:eccfc03edfa4b47bf12cd1',
    messagingSenderId: '529715404420',
    projectId: 'movie-and-tv-series-app',
    storageBucket: 'movie-and-tv-series-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrkV7KqZYotPpZ4wXPQFMveh_KaqqTO0I',
    appId: '1:529715404420:ios:fbd31ad602c16de4f12cd1',
    messagingSenderId: '529715404420',
    projectId: 'movie-and-tv-series-app',
    storageBucket: 'movie-and-tv-series-app.appspot.com',
    iosClientId: '529715404420-4bdajjg5hlbmdr9f4od0341uji7lt3dl.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
